### ISSUE TITLE
Fenêtre d'accès aux recherches de l'addon

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#1]
on prtéfererait une fenêtre dédockable ou un placement dans la barre d'outils pour une meilleure visibilité

**Comment by fvanderbiest** [comment]
OK, j'avais fait comme ça parce que dans les specs on avait dit "Sous réserve de faisabilité, l’interface de recherche se situera au sein de l’interface mapfishapp, dans le cadre en bas à droite de la carte, en premier onglet." et ça me semblait cohérent avec le fait de regrouper au même endroit les outils de localisation.

Pour un placement dans la barre d'outils, on a déjà fait ça dans l'addon quicksearch (financé par Le-Puy-en-Velay), cf https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/addons/quicksearch/manifest.json#L6

@jdenisgiguere pourra regarder ça si vous confirmez cette demande.

**Comment by fjacon** [comment]
@catmorales pourras-tu confirmer ? merci bien.

**Comment by MaelREBOUX** [comment]
On confirme.

**Comment by jdenisgiguere** [comment]
Une solution est proposée dans a3ca28abc66a1bedb88dcdefb2920c85698d2e8d. 
![rva_toolbar](https://cloud.githubusercontent.com/assets/973241/15225570/f3821668-184c-11e6-9036-4dbd9c8bdd5b.png)

**Comment by MaelREBOUX** [comment]
Vu d'ici ça convient. A voir en vrai maintenant.

Prévoir que là où on voit écrit "RVA" ça devienne (proposition) un menu dropdown qui permette de filtrer à la commuen cf #3

**Comment by MaelREBOUX** [comment]
c'est OK : @catmorales si ok pour toi aussi on ferme ce ticket.

**Comment by catmorales** [comment]
ok pour moi aussi
