### ISSUE TITLE
liste auto-complétion : rajouter nom de la commune

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#11]
Ca prend forme !
Il faut impérativement rajouter le nom de la commune :

![screenshot162](https://cloud.githubusercontent.com/assets/6370443/15385210/46fc27fe-1da0-11e6-8c94-caba769d002c.png)

[nom de la voie], [nom de la commune]

Cela va demander à faire une requête getcities. Pas optimal, j'ai donc créé https://github.com/sigrennesmetropole/api_rva/issues/1

**Comment by catmorales** [comment]
J'ai mis @jquiltu sur cette évolution de l'api-rva
