### ISSUE TITLE
liste auto-complétion : comportement recherche 1 voie

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#12]
Recherches dans la zone de recherche :
paris  -> rien
rennes -> rien
rennes% -> ok
rennes[espace] -> ok
bréhat -> rien
bréhat% -> ok

Visiblement, si on ne tape pas d'espace ou %, la recherche n'est pas déclenchée.
Je propose qu'un "event listener" lance la recherche si aucune frappe n'est faite au bout de 2 s.

**Comment by jdenisgiguere** [comment]
L'option `"minChars": 7` détermine le nombre caractères requis avant de lancer la recherche. Présentement la recherche est lancée lorsque le septième caractère est saisi. La valeur peut être diminuée, à 4 par exemple, si nous sommes près à vivre avec une recherche sur "rue ". L'event listener nous laisserait devant la même situation.

**Comment by MaelREBOUX** [comment]
Alors on passe `"minChars"` à 4.
