### ISSUE TITLE
zone de recherche : pb gestion caractère échappement

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#13]
ou un truc du genre : les noms de communes comportant un apostrophe sont écorchés :

![screenshot164](https://cloud.githubusercontent.com/assets/6370443/15385662/59230b0c-1da3-11e6-9ff2-10d04c25cbb3.png)

**Comment by fvanderbiest** [comment]
Ce qui est étrange c'est que la liste déroulante l'affiche bien, alors que le contenu de la combo est erroné...

L'API renvoie

```
"addr3":"13 Rue de la Poste, l&#039;Hermitage"
```

Aussi il faut prévoir un urldecode qqpart...

**Comment by jdenisgiguere** [comment]
La valeur affichée dans le combobox ne peut pas être du HTML : 

@fvanderbiest, est-ce que nous avons déjà dans nos cartons une fonction qui fait
var replaceCharCodes = function(str) {
    return str.replace(/&#(\d+);?/g, function() {
        return String.fromCharCode(arguments[1])
    });
}
?

Sinon, est-ce qu'elle aurait sa place dans GEOR_util.js ?

**Comment by jdenisgiguere** [comment]
Note d'implémentation: Il serait préférable de faire le changement dans le store pour que les étiquettes OpenLayers en bénéficient.

**Comment by fvanderbiest** [comment]
> Sinon, est-ce qu'elle aurait sa place dans GEOR_util.js ?

oui !

**Comment by jdenisgiguere** [comment]
Une solution est proposée dans 20f9bebf997bac3a0714c8e6c2deb4501f390852.

À tester.

**Comment by fvanderbiest** [comment]
je valide

**Comment by MaelREBOUX** [comment]
ok également
