### ISSUE TITLE
Fenêtre des adresses dans la voie

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#15]
Titre de la fenêtre, changer par "Adresses dans la voie".

Les textes des boutons sont en anglais. Mettre "Exporter" et "Fermer". Pb internationalisation add-on pas finie ?

Les noms des champs / attributs doivent être (respecter casse) :
- insee
- id adresse
- num
- ext
- bât
- adresse complète

**Comment by MaelREBOUX** [comment]
https://github.com/sigrennesmetropole/addon_rva/blob/master/js/main.js#L224

Il manque le "e" à "id_adresse"

**Comment by fvanderbiest** [comment]
je valide

**Comment by MaelREBOUX** [comment]
moi aussi
