### ISSUE TITLE
Fichier export des adresses

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#16]
En cohérence avec #15 et la base de données, les noms des champs / attributs doivent être (respecter casse) :
- insee
- id_adr
- numero
- extension
- batiment
- adr_complete

**Comment by jdenisgiguere** [comment]
Should be fixed by 9d91465f1fa8e9796216430ae96a726d0058f946 with https://github.com/sigrennesmetropole/addon_rva/blob/9d91465f1fa8e9796216430ae96a726d0058f946/js/main.js#L246

**Comment by fvanderbiest** [comment]
Je valide

**Comment by MaelREBOUX** [comment]
moi aussi.
