### ISSUE TITLE
label des adresses

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#17]
utiliser l'attribut **addr1** qui ne contient que numéro, extension et bâtiment.

**Comment by jdenisgiguere** [comment]
Should be fixed by 9d91465 .

**Comment by MaelREBOUX** [comment]
je ne vois pas cette correction sur la PF de test

**Comment by fvanderbiest** [comment]
déployé sur test

**Comment by MaelREBOUX** [comment]
ok
