### ISSUE TITLE
label des emprises des voies

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#18]
A la place de "configuration Projet", essayer en mettant le nom de la voie, soit l'attribut **name** renvoyé par getlanes pour voir ce que ça donne.

Ne rien mettre n'est pas idéal car certaines voies sont toutes petites et en fonction du contenu de la carte, le contour bleu ne permet pas de voir où ça se situe. Le label / l'étiquette attire l'attention.

**Comment by jdenisgiguere** [comment]
@fvanderbiest , je ne comprends pas pourquoi "configuration Projet" apparait.

On devrait plutôt voir "${name}, ${insee}"
https://github.com/sigrennesmetropole/addon_rva/blob/master/manifest.json#L18

Voir ma capture d'écran
![lanes_label](https://cloud.githubusercontent.com/assets/973241/15391233/194043a2-1d8e-11e6-98b8-4a76e89ea22f.png)

**Comment by fvanderbiest** [comment]
> @fvanderbiest , je ne comprends pas pourquoi "configuration Projet" apparait.

Oui, moi non plus, du moins pour le moment ...
J'y regarde.

**Comment by fvanderbiest** [comment]
Toujours KO après ce nouveau déploiement ... je vais essayer de tracer ça plus précisément.

**Comment by fvanderbiest** [comment]
```
fvanderbiest@granier:~/workspace/georchestra/georchestra (master *$%)$ git grep "Configuration Project"
config/pom.xml:   <name>Configuration Project</name>
```

**Comment by fvanderbiest** [comment]
Got it ! 
`${name}` est substitué par le controlleur en charge de la publication dynamique des addons.
ping @pmauduit.

cf "label": "Configuration Project, ${insee}" dans le code source de la page mapfishapp:

``` js
GEOR.config.ADDONS = [{
    "id": "rva_0",
    "enabled": true,
    "title": {
        "de": "RVA",
        "fr": "RVA",
        "en": "RVA",
        "es": "RVA"
    },
    "description": {
        "de": "Trouvez en quelques secondes une adresse avec l'API RVA de Rennes Métropole",
        "fr": "Trouvez en quelques secondes une adresse avec l'API RVA de Rennes Métropole",
        "en": "Trouvez en quelques secondes une adresse avec l'API RVA de Rennes Métropole",
        "es": "Trouvez en quelques secondes une adresse avec l'API RVA de Rennes Métropole"
    },
    "name": "RVA",
    "options": {
        "minChars": 7,
        "laneStyle": {
            "fontColor": "blue",
            "labelOutlineColor": "white",
            "label": "Configuration Project, ${insee}",
            "labelOutlineWidth": 3,
            "fontFamily": "serif",
            "fontSize": 12,
            "strokeColor": "blue",
            "labelYOffset": "15",
            "fillOpacity": 0,
            "strokeWidth": 2
        },
        "laneLabelMaxScaleDenominator": 300000,
        "target": "tbar_10",
        "zoomLevel": 18,
        "addressStyle": {
            "fontColor": "fuchsia",
            "labelOutlineColor": "white",
            "graphicName": "star",
            "label": "${addr2}",
            "labelOutlineWidth": 3,
            "pointRadius": 4,
            "fontSize": 10,
            "strokeColor": "fuchsia",
            "fillOpacity": 0,
            "fontFamily": "serif",
            "labelAlign": "cc",
            "strokeWidth": 2,
            "labelYOffset": "15"
        },
        "addressLabelMaxScaleDenominator": 5000,
        "key": "xxx"
    }
} ...
```

**Comment by fvanderbiest** [comment]
Contourné à court terme en utilisant name2 dans la config

**Comment by MaelREBOUX** [comment]
pb de décodage string :

![screenshot172](https://cloud.githubusercontent.com/assets/6370443/15571454/115b4238-233b-11e6-9944-760ae45cd02a.png)

**Comment by jdenisgiguere** [comment]
name2 ne faisait pas partie des champs décodés car il n'est pas utilisé dans la barre de recherche RVA.  

Je propose un PR qui effectuera le décodage sur les champs name2, nameindex pour les voies et  addr1, addr2 pour les addresses.

**Comment by fvanderbiest** [comment]
Déployé sur test

**Comment by MaelREBOUX** [comment]
ok c'est mieux :
![screenshot228](https://cloud.githubusercontent.com/assets/6370443/15848523/be1ddb60-2c8d-11e6-82e8-f3defc4de8f2.png)
