### ISSUE TITLE
Passage du mode "recherche de voie" au mode "recherche d'adresse" perturbant

### ISSUE THREAD

**Issue by fvanderbiest** [sigrennesmetropole/addon_rva#19]
Il y a un gros problème d'ergonomie actuellement, qui peut aussi se traduire par une exception dans le code client, lié à l'usage de `this.components.destroy();` lors du switch de mode.

Concrètement, ce que l'utilisateur tape peut etre écrasé lors de ce changement de mode.
C'est trop perturbant à mon sens.

**Comment by fvanderbiest** [comment]
Voici le rapport de Jean Denis à ce sujet

# Constat

Tout d'abord, voici le noeud de la problématique : un combobox est associé à un store. On ne peut pas facilement gérer la mise à jour du combobox si le modèle de données du store change. Comme les réponses aux recherches par voie et par adresse sont différentes, tout comme les paramètres à passer en requête, la solution actuelle repose sur l'utilisation de 2 stores différents.

À chaque fois que l'on passe d'un store à l'autre - sous la base d'une analyse d'expression régulière - on détruit le combobox actif et on en crée un nouveau. Le problème de convivialité survient lorsque l'on ramène le focus dans le nouveau combobox. La chaine déjà saisie est en surbrillance et s'efface lorsque l'on continue à saisir le champ.

# Hypothèse 1

On pourrait développer un service web mapfishapp (ex. de  point d'accès : rva/getLocation). Le service web traiterait la requête get avec les paramètres requis et transmettrait les données au service web RVA. Il y a aurait un modèle de données JSON unique pour toute les réponses et on utiliserait les conditions XTemplate pour gérer l'affichage du combobox et choisir les couches OpenLayers avec lesquelles interagir.

Cette hypothèse demande de créer un nouveau service web et de changer pas mal la logique de l'addon (au lieu que la logique métier soit dans la gestion des stores et des combobox, elle devient du côté de la gestion du JSON)

# Hypothèse 2

On pourrait investiguer le comportement d'un store unique, pour lequel on modifierait le proxy selon si les recherches concernent des voies ou des adresses, mais qui contiendraient tous les champs requis pour le traitement des voies _et_ des adresses. On sauve le temps de développement du service web, au cout d'une expérimentation du comportement du store à ce changement. Si ça fonctionne, c'est super. Sinon, on a perdu quelques heures et il faut se rabattre sur une autre piste.

Le travail sur la logique de l'addon demeure.

# Hypothèse 3

Il y a peut-être moyen de hacker la partie finale pour que la saisie de la chaine de caractères se fasse de façon transparente. Je n'ai pas de connaissance assez fine avec ce niveau d'interaction en JavaScript pour proposer une solution. J'ai quand même vu quelques trucs de ce genre sur le Web.

**Comment by fvanderbiest** [comment]
L'hypothèse 1 est hors jeu (temps de dév qui va dépasser nos possibilités).

L'hypothèse 3 me semble peu probable de succès.

L'hypothèse 2 me semble la plus pertinente en l'état actuel.

En cas d'échec, la seule solution serait à mon sens de revenir en mode "onglet dans le coin inférieur droit du visualiseur" ce qui nous permettrait d'y caser 2 combobox différentes : l'une dédiée aux recherches de voies, l'autre dédiée aux recherches d'adresses complètes.

**Comment by MaelREBOUX** [comment]
> À chaque fois [...] on détruit le combobox actif et on en crée un nouveau. Le problème de convivialité survient lorsque l'on ramène le focus dans le nouveau combobox. La chaine déjà saisie est en surbrillance et s'efface lorsque l'on continue à saisir le champ.

On a bien noté une espèce d'écrasement / effacement.

Et une hypothèse 4 qui consisterait à rajouter une case à cocher "voies" pour effectuer à la mano ce switch de combobox et donc de datastore ? Moins ergonomique mais tout reste dans l'addon.

**Comment by fvanderbiest** [comment]
> Et une hypothèse 4 qui consisterait à rajouter une case à cocher "voies" pour effectuer à la mano ce switch de combobox et donc de datastore ? Moins ergonomique mais tout reste dans l'addon.

Ca pourrait aussi se faire.
Mais laissons d'abord une chance à @jdenisgiguere avec le store contenant tous les attributs.

**Comment by jdenisgiguere** [comment]
Je confirme que la piste est porteuse. 

Il reste à retirer le code qui n'est plus utile et surtout vérifier pour l'apparition de régressions.

On peut maintenant passer entre les deux modes de façon transparente.

https://github.com/jdenisgiguere/addon_rva/commit/3c71e09532158fd696d58997214c2a4f401ce40f

**Comment by jdenisgiguere** [comment]
Je crois que la PR #20  règle le problème.

**Comment by MaelREBOUX** [comment]
Hâte de tester. @fvanderbiest tu peux merger STP ?

**Comment by fvanderbiest** [comment]
Mergé dans https://github.com/sigrennesmetropole/addon_rva, récupéré dans votre config avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/a8d518a6acf4c13f7ebef4d6f237911d0fb02903 et en cours de redéploiement sur test avec https://portail-test.sig.rennesmetropole.fr/jenkins/job/georchestra-deploy/231

**Comment by fvanderbiest** [comment]
Sauf que ...
ssh: connect to host github.com port 22: Connection timed out
fatal: The remote end hung up unexpectedly

**Comment by fvanderbiest** [comment]
C'est passé avec https://portail-test.sig.rennesmetropole.fr/jenkins/job/georchestra-deploy/232/

**Comment by fvanderbiest** [comment]
Super, je valide.

**Comment by MaelREBOUX** [comment]
Ca marche très bien : cool.

**Comment by catmorales** [comment]
Merci j'ai testé aussi  super
