### ISSUE TITLE
Recherche par voie incomplète

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#2]
On tape le début du nom d'une voie:
1- l'interface propose plusieurs voies sur l'agglo
 --> liste  de proposition peu pratique car peut être très longue - mélange des voies et des adresses
--> on attends une liste de voies et on a un mélange voies et adresses.
il faut détecter si la saisie commence par du numérique : oui -> getfulladresses / sinon -> getlanes 

2-  mise en évidence  dans la carte de la voie choisie
--> on affiche les points de toutes les adresses de toutes les communes 
--> on attend une BBOX de la voie ou mieux mais peut être trop complexe car pas fourni par l'API la ligne de la voie.

3- affichage du tableau de la liste des adresses de la voie
--> absent
--> un export csv depuis cett eliste serait intéressant pour les communes.

4- recentrage sur une adresse sélectionnée dans la liste du tableau précédent
--> absent car pas de tableau le recentrage se fait directement dans la sélection faite sur la liste de choix mélangée adresses et voies, ce n'est pas ce qui était attendu.

**Comment by catmorales** [comment]
rajouter le idlane dans l'infobulle de la voie (point2)

**Comment by fvanderbiest** [comment]
> il faut détecter si la saisie commence par du numérique : oui -> getfulladresses / sinon -> getlanes

Oui.
Je ne l'ai pas implémenté pour le moment par manque de temps.

@jdenisgiguere pourra regarder ça après avoir traité les autres issues de ce dépôt.

**Comment by fvanderbiest** [comment]
https://docs.google.com/document/d/1egic2XPxlqX682K3_WF3h0yZQatEWjaQfV6NgRsYzxg/edit#heading=h.l83vwedlrqqe pour les specs initiales.

**Comment by jdenisgiguere** [comment]
En cours d'implémentation dans https://github.com/jdenisgiguere/addon_rva/tree/lanes .

La colonne Insee sera remplacée par le nom de la commune.

![adresse_voie](https://cloud.githubusercontent.com/assets/973241/14900464/a740930e-0d5e-11e6-9c5e-21e0a20b16ad.png)

**Comment by catmorales** [comment]
A mon avis, il est inutile de remplacer le code insee par le nom de la commune car cela agrandirait la fenêtre, et le nom de la commune est présent dans l'adresse.
Cet outil est destiné à des professionnels qui savent utiliser les code insee.
@MaelREBOUX  ton avis pour confirmation ?

**Comment by catmorales** [comment]
autrement ça me semble très bien :)

**Comment by MaelREBOUX** [comment]
Je confirme : on laisse le code INSEE, le nom de la commune apparaît dans l'adresse complète.

Manque plus que l'export en fichier CSV et ce sera top !

**Comment by catmorales** [comment]
Bonsoir, je viens de voir l'addon sur notre PF de test . C'est très prometteur :) et ça répond bien. :+1: 
Le tableau  des adresses dans la voie me semble complètement en adéquation avec ce que l'on souhaitait.
L'emplacement me semble très approprié pour les utilisateurs.

3 remarques  que j'ai vu à chaud  mais je laisse mes collègues réagir également demain @pcocheril et @MaelREBOUX :
-  la liste de choix de la recherche par voie ne mentionne pas le nom de la commune donc, il est très difficile de faire le bon choix . Par exemple si on tape "place de la mairie", on obtient:
  ![image](https://cloud.githubusercontent.com/assets/4659829/15364755/04a5e638-1d1e-11e6-9869-d435324de6e2.png)
  On ne sait pas sur quel item  cliquer dans la liste pour aller voir par exemple, la place de la mairie de Mordelles.
- les étiquettes sont très "lourdes", mais je crois que l'on peut paramétrer le zoom d'affichage max donc il suffira de le configurer pour une apparition à grande échelle.
- le terme "Configuration Project" ne devrait pas apparaître sur la carte.

**Comment by MaelREBOUX** [comment]
J'ai préféré créer une issue par petites corrections pour pas surcharger ce fil que l'on peut fermer pour moi :
#13
#14
#15
#16
#17
#18

**Comment by fvanderbiest** [comment]
Vu. Merci Mael.
