### ISSUE TITLE
record fields should not be marked as modified

### ISSUE THREAD

**Issue by fvanderbiest** [sigrennesmetropole/addon_rva#23]
Red triangles are due to https://github.com/sigrennesmetropole/addon_rva/blob/master/js/main.js#L445-L447
![capture du 2016-05-20 11 51 09](https://cloud.githubusercontent.com/assets/265319/15424125/2e9768b8-1e81-11e6-9772-5f1b5804d724.png)

There's an option in the gridPanel to prevent this IIRC

**Comment by jdenisgiguere** [comment]
Something is broken in my fix. Please keep it open.

**Comment by fvanderbiest** [comment]
See http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.grid.GridView-cfg-markDirty
