### ISSUE TITLE
Pb sur longueur de chaîne déclenchant la recherche

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_rva#28]
Bonjour,

Visiblement la recherche ne se déclenche qu'à partir de 7 caractères. Du coup une recherche comme "rouge", "croix" ou "yser" n'aboutit pas.

Je suis surpris car je me souviens avoir eu un échange pour passer ce seuil de déclenchement à 4 caractères.

Pour info on peut contourner en tapant n espaces après la chaîne recherchée.

**Comment by MaelREBOUX** [comment]
https://github.com/sigrennesmetropole/addon_rva/blob/master/config.json#L9  mis à 4. Bizarre.

En attente expertise @catmorales .

**Comment by MaelREBOUX** [comment]
vu : dans la surcharge locale rennes c'était resté à 7 : https://github.com/camptocamp/georchestra-rennes-configuration/blob/15.12/mapfishapp/app/addons/rva/config.json#L9

en attente redéploiement pour check.

**Comment by catmorales** [comment]
C'est fait
