### ISSUE TITLE
Recherche par voie - pas possible de réinitialiser l'affichage

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#29]
Bonjour,
Lorsque l'on fait une recherche par voie,on obtient un résultat (tableau +affichage graphique).
![image](https://cloud.githubusercontent.com/assets/4659829/16682051/c0d9c0e8-44f8-11e6-9806-44f091660df6.png)

La fermeture du tableau ne ré-initilise pas la carte.
Seule une nouvelle sélection, permet de vider celle-ci.
@fvanderbiest  merci de corriger ce bug gênant.

**Comment by MaelREBOUX** [comment]
+1 des utilisateurs l'ont remonté.
La seule façon de "virer" les résultats de recherche c'est un F5. Pas top.

Je propose de faire comme l'outil de mesures avancées et de rajouter un bouton "Effacer" dans la barre d'outils.

![screenshot112](https://cloud.githubusercontent.com/assets/6370443/17320007/9cd1d404-5891-11e6-9148-b9e866e1ea84.png)

**Comment by fvanderbiest** [comment]
Devrait être corrigé en 2b0f7c4

**Comment by MaelREBOUX** [comment]
en attente redéploiement MFapp pour test

**Comment by catmorales** [comment]
MFapp ??? Qu'est ce que ça veut dire ?

**Comment by MaelREBOUX** [comment]
Mapfishapp
MFapp

---

De : Catherine MORALES [notifications@github.com]
Date d'envoi : vendredi 9 septembre 2016 09:50
À : sigrennesmetropole/addon_rva
Cc : REBOUX Maël; Comment
Objet : Re: [sigrennesmetropole/addon_rva] Recherche par voie - pas possible de réinitialiser l'affichage (#29)

MFapp ??? Qu'est ce que ça veut dire ?

**Comment by catmorales** [comment]
- Testé cet été sur test,
- redéployé en intraprod ce jour OK,
- à redéployer en extra prod ce midi.

**Comment by MaelREBOUX** [comment]
Testé et c'est bien plus cool comme ça.
