### ISSUE TITLE
Restriction possible de la recherche sur une commune

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#3]
Proposer (case à cocher) de restreindre la recherche à une commune, cela pourrait améliorer les performances et la visibilité dans la liste d'autocomplétion en cas de nom de rue très courant  (place de la mairie,...).

Pourrait être implémenté avec la commande cmd=getcities&insee=all
prévoir une zone de liste avec autocomplétion, si la liste est vide =insee all

**Comment by fvanderbiest** [comment]
En évolution, en effet

**Comment by jdenisgiguere** [comment]
@fjacon, cette bonification n'est pas prévue au cahier des charges, comment fait-on ?

**Comment by fvanderbiest** [comment]
> @fjacon, cette bonification n'est pas prévue au cahier des charges, comment fait-on ?

standby pour le moment.

**Comment by catmorales** [comment]
inutile , le fonctionnement actuel nous convient bien.
