### ISSUE TITLE
Fenêtre liste d'adresse non redimensionnable

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#30]
Un problème bloquant rencontré aujourd'hui sur un rue disposant d'un grand nombre d'adresses, il est impossible de redimensionner lafenêtre et donc on reste bloqué . Seul CTRL F5 permet de rétablir la situation.

![image](https://cloud.githubusercontent.com/assets/4659829/20175161/af807336-a741-11e6-95b3-df6c168a2a02.png)

**Comment by fvanderbiest** [comment]
Devrait être corrigé avec https://github.com/sigrennesmetropole/addon_rva/commit/d05107e5e8f9e3a7989b24d0cd9f747f85406f07 reporté sur test uniquement avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/954fc4b8d67154178ba316be188fe640839239e1

**Comment by fvanderbiest** [comment]
Je vous laisse mettre à jour le datadir de la machine test ?

**Comment by catmorales** [comment]
OK

**Comment by catmorales** [comment]
Je vois qu'il a été mis à jour lors du redéploiement de rmtr, donc ce n'est pas la peine

**Comment by catmorales** [comment]
Ok c'est bon:
![image](https://cloud.githubusercontent.com/assets/4659829/20662987/226ea31e-b556-11e6-97b5-a33d518dfa6c.png)

**Comment by catmorales** [comment]
A déployer en prod

**Comment by fvanderbiest** [comment]
Est-ce que vous savez comment merger en cascade pour passer qqch en prod ?

**Comment by catmorales** [comment]
Non , moi je met à jour les 2 dépots locaux, puis je copie colle dans le dépot destination les fichiers du dépot source à mettre à jour et je fais
```
git add --all
git commit -m "xxx"
git push origin prod (ou extranet)
```

**Comment by catmorales** [comment]
en me mettant sur les bonnes branches bien sûr ;)

**Comment by fvanderbiest** [comment]
Il y a plus simple.
Admettons qu'on veuille passer en prod intranet ce qui est sur test.
 * on se place dans un dépot
 * on récupère les derniers commits de toutes les branches : `git fetch origin`
 * on se positionne sur la branche cible: `git checkout prod`
 * on la met à jour:  `git pull origin prod`
 * on merge test dans prod (la branche courante): `git merge origin/test`
 * on pousse sur github la branche prod mise à jour: `git push origin prod`

**Comment by fvanderbiest** [comment]
Et on recommence pour mettre à jour l'extranet depuis la prod intranet:
```
git fetch origin
git checkout extranet
git pull origin extranet
git merge origin/prod
git push origin extranet
```

**Comment by catmorales** [comment]
En effet , c'est plus simple et plus sûr.
Par contre, je risque de mettre à jour tous les éléments de test dans prod et je ne souhaite pas remonter rmtr, ni urbanisme) dans prod (pas encore validé). Par conséquent cela m'obligera à désactiver les autres modules dans chaque datadir de prod ?

**Comment by fvanderbiest** [comment]
> Par conséquent cela m'obligera à désactiver les autres modules dans chaque datadir de prod ?

C'est ça, via un autre commit dans la branche de prod intra.

**Comment by catmorales** [comment]
Par contre j'ai un conflit sur rctr:
![image](https://cloud.githubusercontent.com/assets/4659829/20665535/57b3fb28-b560-11e6-8886-987e9c88e4fc.png)

**Comment by fvanderbiest** [comment]
dans ce cas il faut faire `git rm mapfishapp/addons/rctr/config.json` puis `git commit`

**Comment by catmorales** [comment]
fait pour la prod intra

**Comment by catmorales** [comment]
pour l'extranet, je pense que je vais avoir des conflits car il y a des commits de la branche extranet qui n'ont pas été fait dans la branche de prod:
#564905e2fb672b3da82c38068df0190cf8684874
et
4c0a26dfbd6b8ec6c25fced3067e21241fc0f5b8

**Comment by catmorales** [comment]
Il faudrait que l'on évite d'avoir une différence entre prod et extranet dans ce cas. 
@MaelREBOUX  va mettre prod d'équerre pour que l'on ait les mêmes commits que sur extranet par contre merci de vérifier les valeurs de ldapadmin.properties cf #492

**Comment by fvanderbiest** [comment]
> Il faudrait que l'on évite d'avoir une différence entre prod et extranet dans ce cas.

Non, ce n'est pas grave... git sait gérer ça très bien via les merge.

**Comment by catmorales** [comment]
pourtant:
![image](https://cloud.githubusercontent.com/assets/4659829/20674545/b0f82f0a-b589-11e6-8ef5-9a3b79ed9517.png)

**Comment by catmorales** [comment]
https://github.com/camptocamp/georchestra-rennes-configuration/blob/extranet/ldapadmin/ldapadmin.properties#L9 est différent dans les deux cas

**Comment by catmorales** [comment]
donc je suppose que je dois modifier  le fichier dansun éditeur de texte pour corriger la ligne puis:
```
git add ldapadmin/ldapadmin.properties
git commit -m ""
git push origin extranet
```
 je modifie le nom de l'instance sur github (nouveau commit)  pour remettre geOrchestra EXTRANET

**Comment by catmorales** [comment]
Fait sur l'extranet

**Comment by fvanderbiest** [comment]
Et vous pouvez voir sur https://github.com/camptocamp/georchestra-rennes-configuration/network le résultat des merge sur les branches. Personnellement j'apprécie beaucoup cette vision.

**Comment by catmorales** [comment]
Oui en effet, c'est plus concret !
