### ISSUE TITLE
Passage en https de l'API-RVA

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#32]
@fvanderbiest l'API-RVA passe en https et change d'URL . 
http://rva.data.rennes-metropole.fr --> https://api-rva.sig.rennesmetropole.fr
Quelles sont les modifications à apporter à l'addon ?

**Comment by fvanderbiest** [comment]
C'est essentiellement https://github.com/sigrennesmetropole/addon_rva/blob/master/manifest.json#L10 qu'il faut modifier.

**Comment by catmorales** [comment]
Visiblement ça ne suffit pas car nous avons fait la redirection à midi et l'addon-rva ne répondait pas. Faut il l'adapter au https ?
Je vais re-tester en le branchant directement. Merci

**Comment by fvanderbiest** [comment]
Est-ce que vous avez noté des messages spécifiques dans la console du navigateur à ce moment là ?

**Comment by catmorales** [comment]
Je viens de rebrancher le portail test directement sur le site en https et ça marche bien. C'est la re-direction qui posait problème :).
@fvanderbiest Je vais en profiter pour changer la clé d'API qui était à ton nom.
