### ISSUE TITLE
Recherche adresse - zoom sur le résultat d'une adresse

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_rva#4]
- le zoom sur une adresse est trop fort (1:267) pas pertinent
- prévoir des étiquettes affichable ou pas (case à cocher)

**Comment by fvanderbiest** [comment]
> le zoom sur une adresse est trop fort (1:267) pas pertinent

OK, nous pouvons rendre ce niveau de zoom configurable (option `zoomLevel` à ajouter dans https://github.com/sigrennesmetropole/addon_rva/blob/master/manifest.json#L7 avec une valeur par défaut de `18` sur l'échelle https://github.com/georchestra/template/blob/15.12/mapfishapp/app/js/GEOR_custom.js#L235-L263)

Ainsi tout utilisateur de cet addon pourra modifier zoomLevel à sa guise dans son `config.json`

**Comment by fvanderbiest** [comment]
> prévoir des étiquettes affichable ou pas (case à cocher)

Je ne comprends pas cette demande

**Comment by MaelREBOUX** [comment]
> >  prévoir des étiquettes affichable ou pas (case à cocher)
> 
> Je ne comprends pas cette demande

Cela veut dire qu'en plus des étoiles violettes il faut afficher aux grandes échelles un label / une étiquette qui utilise l'attribut **addr1** renvoyé par l'API RVA.

Les propriétés de stylage doivent être configurable ainsi que le niveau de zoom où c'est actif.

Pour simplifier on peut se passer de la fonctionnalité qui permet à l'utilisateur de choisir de voir ou de ne pas voir ces étiquettes. Le but est de voir le résultat.

**Comment by jdenisgiguere** [comment]
La PR https://github.com/sigrennesmetropole/addon_rva/pull/7 permet de configurer le niveau de zoom. 

Des développements supplémentaires sont requis pour l'ajout d'une étiquette aux échelles plus grossières.

**Comment by fvanderbiest** [comment]
> Les propriétés de stylage doivent être configurables

C'est déjà le cas : cf le [README](https://github.com/sigrennesmetropole/addon_rva/blob/master/README.md)

Pour l'ajout d'une étiquette, l'administrateur peut choisir un style type

``` json
{"strokeColor": "#ffff00", "fillColor": "#ffff00", "label": "${addr1}", "labelYOffset": "15","labelOutlineColor": "white", "labelOutlineWidth": 3}
```

Je ne pense pas qu'il y ait de dev à faire ici.
@jdenisgiguere tu confirmes ?

**Comment by jdenisgiguere** [comment]
Il est effectivement possible d'afficher l'étiquette sans modifications au code.  D'après ma compréhension des styles OpenLayers, il n'est pas possible d'intégrer la condition relative à l'échelle sans développement supplémentaire.

Un support élémentaire pour avec un dénominateur d'échelle maximal  sera intégré dans la résolution de l'anomalie https://github.com/sigrennesmetropole/addon_rva/issues/2 .

**Comment by catmorales** [comment]
Il est difficile pour nous de comprendre sans le voir. Pourriez vous nous installer l'addon-rva sur la plateforme de test ? Merci

**Comment by MaelREBOUX** [comment]
Je reformule pour qu'on se comprenne tous.
Il faudrait les 2 styles (graphic + label) dans le fichier de conf https://github.com/sigrennesmetropole/addon_rva/blob/master/config.json 

**graphicStyle** existe déjà, rajouter un **labelStyle**

```
"options": {
        "key": "xxxx",
        "minChars": 7,
        "graphicStyle": {
            "graphicName": "star",
            "pointRadius": 4,
            "strokeColor": "fuchsia",
            "strokeWidth": 2,
            "fillOpacity": 0
        },
        "labelStyle": {
            "strokeColor": "#ffff00", 
            "fillColor": "#ffff00",
            "label": "${addr1}",
            "labelYOffset": "15",
            "labelOutlineColor": "white",
             "labelOutlineWidth": 3
        }
    },
```

**Comment by fvanderbiest** [comment]
> Pourriez vous nous installer l'addon-rva sur la plateforme de test ?

Je m'en charge

**Comment by jdenisgiguere** [comment]
@MaelREBOUX voici ce que contient maintenant le manifest.json comme default_options: 
https://github.com/jdenisgiguere/addon_rva/blob/lanes/manifest.json#L12-L40

Le style pour les voies et les adresses décrit la symobologie des étiquettes.

`laneLabelMaxScaleDenominator`   et `addressLabelMaxScaleDenominator` permettent de spécifier l'échelle la plus grossière à laquelle nous afficherons les étiquettes pour les voies et les adresses respectivement.

Est-ce que cette structure répond à vos besoins?

**Comment by MaelREBOUX** [comment]
vu d'ici ça me semble bien. Reste à tester de visu.

**Comment by fvanderbiest** [comment]
Le ticket n'a plus d'objet à mon sens, merci Jean Denis

**Comment by MaelREBOUX** [comment]
`"zoomLevel": 18`

Je ne constate rien visuellement sur la PF de test : ça ne zoome pas au 1 : 2 133 (equiv zoom-level 18)

**Comment by jdenisgiguere** [comment]
@MaelREBOUX , d'après ma compréhension des spécifications, le zoom devrait s'appliquer uniquement  à partir du popup affiché lorsque l'on recherche une adresse. La sélection d'une adresse dans le tableau d'adresses devrait recentrer la carte sur cette adresse.

Observez-vous un comportement différent?

**Comment by MaelREBOUX** [comment]
Exemple avec une recherche "3 impasse", une longue liste de propositions apparaît :

![screenshot179](https://cloud.githubusercontent.com/assets/6370443/15604639/bdfaa33c-2401-11e6-82a9-999be19b9e97.png)

On en choisit une dans la liste -> il ne reste que un seul item sur la carte avec la fenêtre informative.

![screenshot180](https://cloud.githubusercontent.com/assets/6370443/15604649/cb544cfe-2401-11e6-88ab-7afceddb9147.png)

Pour moi : une fois que l'on a une adresse complète dans la zone de recherche pcq on l'a sélectionné dans la liste, ça doit zoomer automatiquement sur l'adresse choisie.

On a un clic de trop pour le moment. Il faut tendre vers le même comportement que la recherche dans G Maps : saisie -> liste de choix -> choix -> zoom

Je consulte les collègues pour avis.

**Comment by catmorales** [comment]
On laisse comme cela pour le moment. A prévoir éventuellement en évolution

**Comment by MaelREBOUX** [comment]
Oui : il y a du pour et du contre sur les 2 comportements. On verra les retours utilisateurs ultérieurement.

**Comment by catmorales** [comment]
revue d'aujourd'hui:
* en ce qui concerne le niveau de zoom c'est paramétrable : j eviens de le passer au niveau 19 sur la PF de test --> OK
* en ce qui concerne les modifications graphiques des étiquettes aussi:
```
"addressStyle": {
            "graphicName": "circle",
            "pointRadius": 8,
            "strokeColor": "white",
            "strokeWidth": 1,
            "fillOpacity": 1,
            "label": "${addr2}",
            "fontColor": "black",
            "fontSize": 10,
            "fontFamily": "serif",
            "labelAlign": "cc",
            "labelYOffset": "15",
            "labelOutlineColor": "white",
            "labelOutlineWidth": 2
        }
```

 donc je ferme ce ticket.
En ce qui concerne le comportement de zoom , cela nous convient pour le moment. Je ferme ce ticket. On en rouvrira un si nécessaire.
