### ISSUE TITLE
Content-type de la réponse RVA devrait être "application/json" 

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/addon_rva#6]
Lorsqu'une requête est transmise au RVA avec le paramètre `format=json`, le Content-Type attendu est `application/json`. Présentement, le Content-Type retourné est `text/json; charset=utf-8`.

Voir par exemple http://rva.data.rennes-metropole.fr/?query=Rue%20de%20l&key=XXXX&version=1.0&format=json&epsg=4326&cmd=getfulladdresses .

Le mauvais Content-Type engendre une erreur 403 de l'OGCProxy.

**Comment by jquiltu** [comment]
Bonjour,
Le content type est corrigé: 
`Content-Type:application/x-www-form-urlencoded; charset=UTF-8`

Néanmoins la correction n'est pas visible avec votre exemple ( [http://rva.data.rennes-metropole.fr/?query=Rue%20de%20l&key=XXXX&version=1.0&format=json&epsg=4326&cmd=getfulladdresses] ) car les retours d'erreurs sont gérés uniquement en xml.

**Comment by jdenisgiguere** [comment]
Je mets @fvanderbiest  en copie.

**Comment by fvanderbiest** [comment]
Je ne comprends pas ...
Content-Type:application/x-www-form-urlencoded; charset=UTF-8 != application/json

**Comment by jquiltu** [comment]
J'ai fait une erreur de copier/coller je crois...
Voici le content type retourné pour un requete de type "getlanes"

`Content-Type:application/json; charset=utf-8`

Est ce bien le comportement souhaité ? @fvanderbiest

**Comment by fvanderbiest** [comment]
Il est inutile de préciser `charset=utf-8`, c'est le charset par défaut de `application/json`

Merci.
